### ISSUE TITLE
swo_notification resource webhook error

### ISSUE THREAD

**Issue by jaimeviloria** [solarwinds/terraform-provider-swo#94]
There is what looks like a typo on the documentation and somewhere in the provider

https://registry.terraform.io/providers/solarwinds/swo/latest/docs/resources/notification#auth_header_hame

when using the resource the following error is provided

> │ An unexpected error was encountered trying to convert tftypes.Value into provider.notificationSettingsWebhook. This is always an error in the provider. Please report the following to the provider developer:
│
│ mismatch between struct and object: Struct defines fields not found in object: auth_header_name. Object defines fields not found in struct: auth_header_hame.

**Comment by grepory** [comment]
@jaimeviloria Thanks for pointing this out. Looks like a simple typo. We'll fix this and get it out in the next release.

**Comment by grepory** [comment]
Fixed in next release. Thanks!
